"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const router = useRouter();

  // Check token on mount
  useEffect(() => {
    const token = localStorage.getItem("token");
    setIsLoggedIn(!!token);
  }, []);

  // Logout handler
  const handleLogout = () => {
    localStorage.removeItem("token");
    setIsLoggedIn(false);
    router.push("/"); // Back to landing page
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navigation Bar */}
        <nav className="bg-gray-800 text-white p-4 flex items-center">
          {/* Logo Section */}
          <Link href="/" className="flex items-center">
            <Image src="/logo.png" alt="Logo" width={40} height={40} />
            <span className="ml-2 font-bold text-lg">CAAT</span>
          </Link>

          {/* Auth Links or Logout */}
          <div className="ml-auto flex space-x-4">
            {isLoggedIn ? (
              <button
                onClick={handleLogout}
                className="hover:underline text-red-300"
              >
                Logout
              </button>
            ) : (
              <>
                <Link href="/auth/login" className="hover:underline">
                  Login
                </Link>
                <Link href="/auth/register" className="hover:underline">
                  Register
                </Link>
              </>
            )}
          </div>
        </nav>

        <main>{children}</main>
      </body>
    </html>
  );
}
